### ISSUE TITLE
Error when using v2

### ISSUE THREAD

**Issue by MineRickStar** [ZeroOne3010/yetanotherhueapi#60]
hi, just found out about this API, but when using v2 in Eclipse I always get the error

`[ForkJoinPool.commonPool-worker-9] INFO io.github.zeroone3010.yahueapi.HueBridgeConnectionBuilder - [{"success":{"username":"7pai1jaNCJzEPLsigj1ynlerO-fpBYOz8CK5zB9j"}}]

Store this API key for future use: 7pai1jaNCJzEPLsigj1ynlerO-fpBYOz8CK5zB9j

Exception in thread "main" io.github.zeroone3010.yahueapi.HueApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.github.zeroone3010.yahueapi.v2.Hue.refresh(Hue.java:135)
	at io.github.zeroone3010.yahueapi.v2.Hue.<init>(Hue.java:103)
	at io.github.zeroone3010.yahueapi.v2.Hue.<init>(Hue.java:116)
	`

I am using eclipse 12/22. And Java Version 1.8.
If I am using the deprecated version 1 it all works and I can control all my hue stuff.
Don't know if I am doing something wrong or what the problem is

**Comment by ZeroOne3010** [comment]
Hey, thanks for submitting an issue! Is this with the version you get from the Maven repository? Could you possibly please try with the latest version from this repository?

**Comment by ZeroOne3010** [comment]
There was indeed an issue with older bridges that still have a self-signed certificate! Signify intends to update all bridges, but they're not there yet. Please find the fresh-from-the-oven version 3.0.0-beta-2 from the Maven repository and try with that now! :pray: I'm confident it will solve your issues, but in case it won't, don't hesitate to reopen this issue!
